name: create issue

on:
  schedule:
    - cron:  '0 0 1 */3 *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: create issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}