name: create issue

on:
  schedule:
    - cron:  '0 0 1 */3 *'

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: create issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/create_issue.md
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}